"""empty message

Revision ID: 9a00ae26c6f8
Revises: ad960f0703b5
Create Date: 2016-10-17 01:03:21.138187

"""

# revision identifiers, used by Alembic.
revision = '9a00ae26c6f8'
down_revision = 'ad960f0703b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar')
    ### end Alembic commands ###
